// Code generated by goyacc - DO NOT EDIT.

package configparser

import __yyfmt__ "fmt"

import (
	"fmt"
	"time"

	"github.com/PlakarKorp/plakar/scheduler"
)

func Parser(lexer yyLexer) *ConfigParser {
	return lexer.(*ConfigParser)
}

type yySymType struct {
	yys       int
	b         bool
	s         string
	i         int64
	task      scheduler.Task
	schedule  scheduler.Schedule
	schedules []scheduler.Schedule
	times     []scheduler.Time
	strings   []string
	size      float64
	duration  time.Duration
	time      scheduler.Time
	datemask  scheduler.DateMask
	month     time.Month
	err       error
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault   = 57384
	yyEofCode   = 57344
	AND         = 57368
	AT          = 57370
	BACKUP      = 57349
	BEFORE      = 57361
	CATEGORY    = 57355
	CHECK       = 57350
	DAY         = 57369
	DURATION    = 57378
	ENVIRONMENT = 57356
	ERROR       = 57376
	EVERY       = 57371
	EXCLUDE     = 57363
	FROM        = 57365
	INTEGER     = 57373
	JOB         = 57358
	LATEST      = 57360
	MAINTENANCE = 57353
	MONTH       = 57381
	NAME        = 57354
	OFF         = 57348
	ON          = 57347
	PERIMETER   = 57357
	REFERENCE   = 57375
	REPORTING   = 57346
	RESTORE     = 57351
	RETENTION   = 57364
	SINCE       = 57362
	SIZE        = 57377
	STRING      = 57374
	SYNC        = 57352
	TAG         = 57359
	TIME        = 57379
	TO          = 57366
	UNTIL       = 57372
	WEEKDAY     = 57380
	WITH        = 57367
	yyErrCode   = 57345

	yyMaxDepth = 200
	yyTabOfs   = -57
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		10:    0,  // '\n' (53x)
		57370: 1,  // AT (41x)
		57371: 2,  // EVERY (41x)
		57364: 3,  // RETENTION (15x)
		57374: 4,  // STRING (14x)
		57347: 5,  // ON (13x)
		57375: 6,  // REFERENCE (11x)
		57363: 7,  // EXCLUDE (10x)
		57359: 8,  // TAG (10x)
		44:    9,  // ',' (8x)
		57366: 10, // TO (7x)
		57398: 11, // repository (6x)
		57344: 12, // $end (5x)
		57365: 13, // FROM (5x)
		57358: 14, // JOB (5x)
		57346: 15, // REPORTING (5x)
		57372: 16, // UNTIL (5x)
		57379: 17, // TIME (4x)
		57408: 18, // time (4x)
		57349: 19, // BACKUP (3x)
		57350: 20, // CHECK (3x)
		57388: 21, // duration (3x)
		57378: 22, // DURATION (3x)
		57353: 23, // MAINTENANCE (3x)
		57351: 24, // RESTORE (3x)
		57352: 25, // SYNC (3x)
		57367: 26, // WITH (3x)
		57396: 27, // optnl (2x)
		57399: 28, // schedule (2x)
		57402: 29, // schedule_time (2x)
		57380: 30, // WEEKDAY (2x)
		57411: 31, // weekday (2x)
		57382: 32, // $@1 (1x)
		57383: 33, // $@2 (1x)
		57385: 34, // backup_opt (1x)
		57386: 35, // backup_opts (1x)
		57387: 36, // destination (1x)
		57389: 37, // from_time (1x)
		57390: 38, // grammar (1x)
		57391: 39, // job (1x)
		57392: 40, // maintenance_opt (1x)
		57393: 41, // maintenance_opts (1x)
		57348: 42, // OFF (1x)
		57395: 43, // on_off (1x)
		57397: 44, // reporting (1x)
		57400: 45, // schedule_days (1x)
		57401: 46, // schedule_list (1x)
		57404: 47, // source (1x)
		57406: 48, // sync_direction (1x)
		57407: 49, // task (1x)
		57409: 50, // time_list (1x)
		57410: 51, // until_time (1x)
		57412: 52, // weekday_list (1x)
		57384: 53, // $default (0x)
		57368: 54, // AND (0x)
		57361: 55, // BEFORE (0x)
		57355: 56, // CATEGORY (0x)
		57369: 57, // DAY (0x)
		57356: 58, // ENVIRONMENT (0x)
		57376: 59, // ERROR (0x)
		57345: 60, // error (0x)
		57373: 61, // INTEGER (0x)
		57360: 62, // LATEST (0x)
		57381: 63, // MONTH (0x)
		57394: 64, // month (0x)
		57354: 65, // NAME (0x)
		57357: 66, // PERIMETER (0x)
		57362: 67, // SINCE (0x)
		57403: 68, // size (0x)
		57377: 69, // SIZE (0x)
		57405: 70, // source_list (0x)
	}

	yySymNames = []string{
		"'\\n'",
		"AT",
		"EVERY",
		"RETENTION",
		"STRING",
		"ON",
		"REFERENCE",
		"EXCLUDE",
		"TAG",
		"','",
		"TO",
		"repository",
		"$end",
		"FROM",
		"JOB",
		"REPORTING",
		"UNTIL",
		"TIME",
		"time",
		"BACKUP",
		"CHECK",
		"duration",
		"DURATION",
		"MAINTENANCE",
		"RESTORE",
		"SYNC",
		"WITH",
		"optnl",
		"schedule",
		"schedule_time",
		"WEEKDAY",
		"weekday",
		"$@1",
		"$@2",
		"backup_opt",
		"backup_opts",
		"destination",
		"from_time",
		"grammar",
		"job",
		"maintenance_opt",
		"maintenance_opts",
		"OFF",
		"on_off",
		"reporting",
		"schedule_days",
		"schedule_list",
		"source",
		"sync_direction",
		"task",
		"time_list",
		"until_time",
		"weekday_list",
		"$default",
		"AND",
		"BEFORE",
		"CATEGORY",
		"DAY",
		"ENVIRONMENT",
		"ERROR",
		"error",
		"INTEGER",
		"LATEST",
		"MONTH",
		"month",
		"NAME",
		"PERIMETER",
		"SINCE",
		"size",
		"SIZE",
		"source_list",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {38, 0},
		2:  {38, 2},
		3:  {38, 3},
		4:  {38, 3},
		5:  {27, 0},
		6:  {27, 2},
		7:  {44, 2},
		8:  {39, 6},
		9:  {32, 0},
		10: {49, 6},
		11: {49, 2},
		12: {33, 0},
		13: {49, 5},
		14: {49, 4},
		15: {49, 4},
		16: {47, 1},
		17: {47, 1},
		18: {70, 1},
		19: {70, 2},
		20: {36, 1},
		21: {36, 1},
		22: {11, 1},
		23: {11, 1},
		24: {35, 0},
		25: {35, 2},
		26: {34, 2},
		27: {34, 2},
		28: {34, 2},
		29: {41, 0},
		30: {41, 2},
		31: {40, 2},
		32: {48, 1},
		33: {48, 1},
		34: {48, 1},
		35: {46, 1},
		36: {46, 2},
		37: {28, 2},
		38: {29, 2},
		39: {29, 4},
		40: {37, 0},
		41: {37, 2},
		42: {51, 0},
		43: {51, 2},
		44: {45, 0},
		45: {45, 2},
		46: {52, 1},
		47: {52, 3},
		48: {50, 1},
		49: {50, 3},
		50: {68, 1},
		51: {21, 1},
		52: {18, 1},
		53: {31, 1},
		54: {64, 1},
		55: {43, 1},
		56: {43, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [83][]uint16{
		// 0
		{56, 12: 56, 14: 56, 56, 38: 58},
		{59, 12: 57, 14: 63, 62, 39: 61, 44: 60},
		{55, 12: 55, 14: 55, 55},
		{139},
		{138},
		// 5
		{5: 136, 42: 137, 135},
		{4: 64},
		{52, 19: 52, 52, 23: 52, 52, 52, 27: 65},
		{66, 19: 68, 69, 23: 70, 71, 72, 49: 67},
		{51, 51, 51, 19: 51, 51, 23: 51, 51, 51},
		// 10
		{52, 52, 52, 27: 109},
		{4: 96, 6: 97, 47: 95},
		{4: 74, 6: 75, 11: 94},
		{5: 86},
		{4: 74, 6: 75, 11: 81},
		// 15
		{4: 74, 6: 75, 11: 73},
		{10: 77, 13: 78, 26: 79, 48: 76},
		{35, 35, 35, 35, 7: 35, 35, 10: 35, 13: 35, 26: 35},
		{34, 34, 34, 34, 7: 34, 34, 10: 34, 13: 34, 26: 34},
		{4: 74, 6: 75, 11: 80},
		// 20
		{4: 25, 6: 25},
		{4: 24, 6: 24},
		{4: 23, 6: 23},
		{42, 42, 42},
		{10: 82},
		// 25
		{4: 84, 6: 85, 36: 83},
		{43, 43, 43},
		{37, 37, 37},
		{36, 36, 36},
		{4: 74, 6: 75, 11: 87},
		// 30
		{45, 45, 45, 45, 33: 88},
		{28, 28, 28, 28, 41: 89},
		{44, 44, 44, 91, 40: 90},
		{27, 27, 27, 27},
		{21: 92, 93},
		// 35
		{26, 26, 26, 26},
		{6, 6, 6, 6, 5: 6, 7: 6, 6, 13: 6, 16: 6},
		{46, 46, 46},
		{10: 98},
		{10: 41},
		// 40
		{10: 40},
		{4: 74, 6: 75, 11: 99},
		{48, 48, 48, 48, 7: 48, 48, 32: 100},
		{33, 33, 33, 33, 7: 33, 33, 35: 101},
		{47, 47, 47, 105, 7: 104, 103, 34: 102},
		// 45
		{32, 32, 32, 32, 7: 32, 32},
		{4: 108},
		{4: 107},
		{21: 106, 93},
		{29, 29, 29, 29, 7: 29, 29},
		// 50
		{30, 30, 30, 30, 7: 30, 30},
		{31, 31, 31, 31, 7: 31, 31},
		{66, 113, 114, 28: 111, 112, 46: 110},
		{49, 113, 114, 28: 134, 112},
		{22, 22, 22},
		// 55
		{13, 13, 13, 5: 128, 45: 127},
		{17: 119, 124, 50: 123},
		{21: 115, 93},
		{17, 17, 17, 5: 17, 13: 117, 16: 17, 37: 116},
		{15, 15, 15, 5: 15, 16: 121, 51: 120},
		// 60
		{17: 119, 118},
		{16, 16, 16, 5: 16, 16: 16},
		{5, 5, 5, 5: 5, 9: 5, 16: 5},
		{18, 18, 18, 5: 18},
		{17: 119, 122},
		// 65
		{14, 14, 14, 5: 14},
		{19, 19, 19, 5: 19, 9: 125},
		{9, 9, 9, 5: 9, 9: 9},
		{17: 119, 126},
		{8, 8, 8, 5: 8, 9: 8},
		// 70
		{20, 20, 20},
		{30: 131, 130, 52: 129},
		{12, 12, 12, 9: 132},
		{11, 11, 11, 9: 11},
		{4, 4, 4, 9: 4},
		// 75
		{30: 131, 133},
		{10, 10, 10, 9: 10},
		{21, 21, 21},
		{50},
		{2},
		// 80
		{1},
		{53, 12: 53, 14: 53, 53},
		{54, 12: 54, 14: 54, 54},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 60

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 7:
		{
			Parser(yylex).reporting = yyS[yypt-0].b
		}
	case 8:
		{
			if Parser(yylex).HasJob(yyS[yypt-4].s) {
				Parser(yylex).Error(fmt.Sprintf("job %q already defined", yyS[yypt-4].s))
				goto ret1
			}
			Parser(yylex).PushJob(yyS[yypt-4].s, yyS[yypt-2].task, yyS[yypt-0].schedules)
		}
	case 9:
		{
			Parser(yylex).MakeBackupTask(yyS[yypt-0].s, yyS[yypt-2].s)
		}
	case 10:
		{
			yyVAL.task = Parser(yylex).currentTask
		}
	case 11:
		{
			yyVAL.task = Parser(yylex).MakeCheckTask(yyS[yypt-0].s)
		}
	case 12:
		{
			Parser(yylex).MakeMaintenanceTask(yyS[yypt-0].s)
		}
	case 13:
		{
			yyVAL.task = Parser(yylex).currentTask
		}
	case 14:
		{
			yyVAL.task = Parser(yylex).MakeRestoreTask(yyS[yypt-2].s, yyS[yypt-0].s)
		}
	case 15:
		{
			yyVAL.task = Parser(yylex).MakeSyncTask(yyS[yypt-2].s, yyS[yypt-1].s, yyS[yypt-0].s)
		}
	case 16:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 17:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 18:
		{
			yyVAL.strings = append(make([]string, 0, 5), yyS[yypt-0].s)
		}
	case 19:
		{
			yyVAL.strings = append(yyS[yypt-1].strings, yyS[yypt-0].s)
		}
	case 20:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 21:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 22:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 23:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 26:
		{
			task := Parser(yylex).currentTask.(*scheduler.BackupTask)
			task.Cmd.Tags = yyS[yypt-0].s
		}
	case 27:
		{
			task := Parser(yylex).currentTask.(*scheduler.BackupTask)
			task.Cmd.Excludes = append(task.Cmd.Excludes, yyS[yypt-0].s)
		}
	case 28:
		{
			task := Parser(yylex).currentTask.(*scheduler.BackupTask)
			task.Retention = yyS[yypt-0].duration
		}
	case 31:
		{
			task := Parser(yylex).currentTask.(*scheduler.MaintenanceTask)
			task.Retention = yyS[yypt-0].duration
		}
	case 32:
		{
			yyVAL.s = "to"
		}
	case 33:
		{
			yyVAL.s = "from"
		}
	case 34:
		{
			yyVAL.s = "with"
		}
	case 35:
		{
			yyVAL.schedules = append(yyVAL.schedules, yyS[yypt-0].schedule)
		}
	case 36:
		{
			yyVAL.schedules = append(yyS[yypt-1].schedules, yyS[yypt-0].schedule)
		}
	case 37:
		{
			yyVAL.schedule = yyS[yypt-1].schedule.WithDateMask(yyS[yypt-0].datemask)
		}
	case 38:
		{
			yyVAL.schedule = Parser(yylex).MakeScheduleAt(yyS[yypt-0].times)
		}
	case 39:
		{
			yyVAL.schedule = Parser(yylex).MakeScheduleEvery(yyS[yypt-2].duration, yyS[yypt-1].time, yyS[yypt-0].time)
		}
	case 40:
		{
			yyVAL.time = scheduler.UndefinedTime
		}
	case 41:
		{
			yyVAL.time = yyS[yypt-0].time
		}
	case 42:
		{
			yyVAL.time = scheduler.UndefinedTime
		}
	case 43:
		{
			yyVAL.time = yyS[yypt-0].time
		}
	case 44:
		{
			yyVAL.datemask = scheduler.EveryDay
		}
	case 45:
		{
			yyVAL.datemask = scheduler.EveryDay.SetWeekdayMask(yyS[yypt-0].datemask)
		}
	case 46:
		{
			yyVAL.datemask = yyS[yypt-0].datemask
		}
	case 47:
		{
			yyVAL.datemask = yyS[yypt-2].datemask | yyS[yypt-0].datemask
		}
	case 48:
		{
			yyVAL.times = append(make([]scheduler.Time, 0, 1), yyS[yypt-0].time)
		}
	case 49:
		{
			yyVAL.times = append(yyS[yypt-2].times, yyS[yypt-0].time)
		}
	case 50:
		{
			yyVAL.size = yyS[yypt-0].size
		}
	case 51:
		{
			yyVAL.duration = yyS[yypt-0].duration
		}
	case 52:
		{
			yyVAL.time = yyS[yypt-0].time
		}
	case 53:
		{
			yyVAL.datemask = yyS[yypt-0].datemask
		}
	case 54:
		{
			yyVAL.month = yyS[yypt-0].month
		}
	case 55:
		{
			yyVAL.b = true
		}
	case 56:
		{
			yyVAL.b = false
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
